{"id": 3173, "title": "Ticket #3173: glexec cleanup fails if proxy is missing", "description": "<blockquote>\nRUST ticket contents:\n\n<p></p><div class=\"verbatim\">\n<pre>&gt; Hi Dan and Zach.\n&gt;\n&gt; I think I have found a logical bug in the Condor-glexec interface.\n&gt;\n&gt; The problem is\n&gt; condor_glexec_cleanup\n&gt;\n&gt; It fails if the user does a through cleanup of his work area at job termination, e.g. like this:\n&gt; for FILE in `find . -not -name \"*stderr\" -not -name \"*stdout\" `; do rm -rf $FILE; done\n&gt;\n&gt; The net result is a shadow exception, due to the started going belly up with\n&gt; 07/06/12 09:03:57 (pid:17055) GLExecPrivSepHelper::run_script: /data1/condor_local/execute/dir_32278/glide_f32339/main/condor/\nlibexec/condor_glexec_cleanup exited with status 256 and following output:\n&gt; It appears that the value of pthread_mutex_init is 651034992\n&gt; rm: cannot remove `/data1/condor_local/execute/dir_32278/glide_f32339/execute/dir_17055/x509up_u31055': No such file or direct\nory\n&gt; tar: This does not look like a tar archive\n&gt; tar: Error exit delayed from previous errors\n&gt; mv: cannot move `/data1/condor_local/execute/dir_32278/glide_f32339/execute/dir_17055.condor' to `/data1/condor_local/execute/\ndir_32278/glide_f32339/execute/dir_17055/dir_17055.condor': Permission denied\n&gt;\n&gt; 07/06/12 09:03:57 (pid:17055) ERROR \"error changing sandbox ownership to condor\" at line 188 in file /home/condor/execute/dir_\n3605/userdir/src/condor_starter.V6.1/glexec_privsep_helper.linux.cpp\n&gt;\n&gt; I think the offending code is this:\n&gt; \"$GLEXEC\" \"$SH\" -c \"rm \\\"$SANDBOX/$PROXY\\\" &amp;&amp; \\\n&gt;                          tar -C \\\"$SANDBOX\\\" -c . &amp;&amp; \\\n&gt;                          rm -rf \\\"$SANDBOX\\\"\" | \\\n&gt;      tar -C \"$SANDBOX.condor\" -x\n&gt;\n&gt; I.e. if the user deletes the proxy file, everything else fails!\n&gt;\n&gt; I would argue you want to proceed even if the proxy file is not there.\n</pre></div>\n</blockquote>", "remarks": "<blockquote>\n<em>2012-Aug-01 15:38:54 by danb:</em> <br/>\n\nIt appears that this problem was already fixed in <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=1760\" onclick=\"get_ticket_and_populate_wrapper('1760'); return false;\" title=\"privsep chown operation fails on unwritable directories\">#1760</a></span>.  Currently, that ticket claims to have been resolved in 7.6.1, but the commit does not appear in the 7.6 branch.  It appears in the 7.7 branch.</blockquote>", "derived_tickets": "", "attachments": "", "check_ins": "", "type": "defect", "last_change": "2012-Aug-01 15:42", "status": "resolved", "created": "2012-Aug-01 11:53", "fixed_version": "2012-Aug-01 11:53", "broken_version": "v070607", "priority": "3", "subsystem": "Security", "assigned_to": "danb", "derived_from": "", "creator": "zmiller", "rust": "s8190", "customer_group": "cms", "visibility": "public", "notify": "zmiller@cs.wisc.edu", "due_date": "20120815"}