{"id": 481, "title": "Ticket #481: Recovery fails on a DAG that has retried nodes", "description": "<blockquote>\nIf a DAG goes into recovery mode, and has previously retried a node when running \"normally\", DAGMan fails.\n\n<p>If a user tries to recover a dag which contains retired jobs, the\nrecovery fails when dagman encounters the first retried node from the\nprevious DAG. Here's a test case:\n\n</p><p>[dbrown@sugar ~]$ cat jessica.dag\nJOB 1 sleep.sub\nRETRY 1 1\nJOB 2 sleep.sub\nRETRY 2 1\nPARENT 1 CHILD 2\n\n</p><p>[dbrown@sugar ~]$ cat sleep.sub\nuniverse = vanilla\nexecutable = /bin/sleep\narguments = 300\nlog = /tmp/duncantest.log\noutput = sleep.$(cluster).out\nerror = sleep.$(cluster).err\nqueue\n\n</p><p>I started jessica.dag, logged into the node that was running the sleep\njob and sent it a kill -9 so it failed. dagman then re-tried the sleep\njob, as it is supposed to. I then triggered the recovery procedure in\ndagman by doing a condor_hold on the dagman job and then a\ncondor_release once it exited. The new dagman proceeds started up in\nrecovery mode, but failed with the error message\n\n</p><p>5/6 23:24:39 ERROR: node 1: job ID in userlog submit event (2847958.0)\ndoesn't match ID reported earlier by submit command (2847957.0)!\nAborting DAG; set DAGMAN_ABORT_ON_SCARY_SUBMIT to false if you are\n<strong>sure</strong> this shouldn't cause an abort.\n5/6 23:24:39 Aborting DAG...\n5/6 23:24:39 Writing Rescue DAG to jessica.dag.rescue001...</p></blockquote>", "remarks": "<blockquote>\nOkay, I've fixed the actual bug in DAGMan.  I'm putting this ticket into the \"Active\" rather than \"Resolved\" state, though, because the <strong>test</strong> doesn't work correctly yet.  I'm going to also change the severity and priority from 2 and 1 to 4 and 4.\n\n<p>2009-06-05: I've fully implemented the test now, but I'm still leaving the ticket open because we have some indication from LIGO that the problem is not totally fixed.\n\n</p><p>2009-06-11: okay, LIGO has just reported that the problem <strong>is</strong> fixed, so I'm going to close out this ticket (I just resolved the related RUST ticket).</p></blockquote>", "derived_tickets": "", "attachments": "", "check_ins": "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n<tbody><tr><td align=\"right\" valign=\"top\" width=\"160\">2009-May-13 14:53</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"chngview?cn=24785\">[24785]</a></span>: Fixed gittrac <span class=\"ticket\"><a class=\"defer\" href=\"/tickets?ticket=481\" onclick=\"get_ticket_and_populate_wrapper('481'); return false;\" title=\"Recovery fails on a DAG that has retried nodes\">#481</a></span> (recovery fails on a DAG that has retried nodes). Note: I created the job_dagman_retry_recovery test, but it doesn't work right, so I haven't added it to the Imakefile. (The problem is that the script bails out when DAGMan is condor_held, so even though the DAG eventually finishes\u00a0[...]\n (By Kent Wenger )</td></tr>\n</tbody></table>", "type": "defect", "last_change": "2010-Jan-31 13:40", "status": "defer", "created": "2009-May-11 16:13", "fixed_version": "2009-May-11 16:13", "broken_version": "v070202", "priority": "5", "subsystem": "Dag", "assigned_to": "wenger", "derived_from": "", "creator": "wenger", "rust": "a19723", "customer_group": "ligo", "visibility": "public", "notify": "wenger@cs.wisc.edu, psilord@cs.wisc.edu,pcouvare@caltech.edu", "due_date": ""}