{"id": 5014, "title": "Ticket #5014: ssh-to-job hangs schedd?", "description": "<blockquote>\nNOT confirmed to be a problem off my branch, however, see <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=4997\" onclick=\"get_ticket_and_populate_wrapper('4997'); return false;\" title=\"Infinite loop in condor_ssh_to_job\">#4997</a></span>.\n\n<p>condor_ssh_to_job can effectively hang the schedd if it fails to authenticate with Kerberos.\n\n</p><p>Condor_Auth_Kerberos::authenticate eventually calls\n\n</p><p></p><div class=\"verbatim\">\n<pre>condor_read (\n    peer_description=0x233246c \"&lt;128.104.100.29:14489&gt;\", fd=16,\n    buf=0x7fffd2609350 \"\\340Ny\\035\", sz=5, timeout=20, flags=0,\n    non_blocking=false)\n</pre></div>\n\n\n<p>which ends up repeating\n\n</p><p></p><div class=\"verbatim\">\n<pre>04/22/15 16:08:41 (pid:4494) condor_read(): timeout reading 5 bytes from &lt;128.10\n4.100.29:14489&gt;.\n04/22/15 16:08:41 (pid:4494) IO: Failed to read packet header\n04/22/15 16:09:01 (pid:4494) condor_read(): timeout reading 5 bytes from &lt;128.10\n4.100.29:14489&gt;.\n04/22/15 16:09:01 (pid:4494) IO: Failed to read packet header\n04/22/15 16:09:21 (pid:4494) condor_read(): timeout reading 5 bytes from &lt;128.10\n4.100.29:14489&gt;.\n04/22/15 16:09:21 (pid:4494) IO: Failed to read packet header\n</pre></div>\n\n\n<p>in the log for a long time.\n\n</p><p>The client stalls for a long time at the following (D_ALL):\n\n</p><p></p><div class=\"verbatim\">\n<pre>04/22/15 16:13:32 (fd:4) (pid:26222) (D_ALWAYS:2) SharedPortClient: sent connection request to schedd submit-3.batlab.org for shared port id 10722_4af1_8\n04/22/15 16:13:32 (fd:4) (pid:26222) (D_ALWAYS) KERBEROS: No credentials cache found\n</pre></div>\n\n\n<p>GDB reveals\n\n</p><p></p><div class=\"verbatim\">\n<pre>#0  0x00007ff2e91e8098 in poll () from /lib64/libc.so.6\n#1  0x00007ff2ea042ed6 in Selector::execute (this=0x7fff25151ec0)\n    at /home/tlmiller/condor/source/src/condor_utils/selector.cpp:314\n#2  0x00007ff2ea19ebd8 in condor_read (\n    peer_description=0x2481470 \"schedd submit-3.batlab.org\", fd=3,\n    buf=0x7fff25152030 \"(\\261\\031\\352\\362\\177\", sz=5, timeout=300, flags=0,\n    non_blocking=false)\n    at /home/tlmiller/condor/source/src/condor_io/condor_rw.cpp:191\n</pre></div>\n\n\n<p>below a call to\n\n</p><p></p><div class=\"verbatim\">\n<pre>#8  0x00007ff2ea1cb20e in Authentication::handshake (this=0x2486620,\n    my_methods=..., non_blocking=false)\n    at /home/tlmiller/condor/source/src/condor_io/authentication.cpp:1006\n#9  0x00007ff2ea1c8c10 in Authentication::authenticate_continue (\n    this=0x2486620, errstack=0x7fff25153600, non_blocking=false)\n    at /home/tlmiller/condor/source/src/condor_io/authentication.cpp:206\n#10 0x00007ff2ea1c896f in Authentication::authenticate_inner (this=0x2486620,\n    hostAddr=0x24679b0 \"&lt;128.104.100.22:9150?addrs=[2607:f388:107c:501:1b:21ff:feca:51f0]:9150+128.104.100.22:9150&amp;noUDP&amp;rewrite=2607:f388:107c:501:1b:21ff:feca:51f0&amp;sock=10722_4af1_8&gt;\", auth_methods=0x246a900 \"FS,KERBEROS,GSI\",\n    errstack=0x7fff25153600, timeout=-1, non_blocking=false)\n    at /home/tlmiller/condor/source/src/condor_io/authentication.cpp:162\n</pre></div>\n\n\n<p>Retesting with SEC_DEFAULT_AUTHENTICATION_METHODS = FS, CLAIMTOBE avoids the problem.\n\n</p><p>The condor_ssh_to_job call is from a different machine, so FS can't work.</p></blockquote>", "remarks": "<blockquote>\n<em>2015-Apr-22 16:41:50 by tlmiller:</em> <br/>\n\nSwitching the client to FS, GSI changed the error message but didn't solve the problem.\n\n<p>Running\n\n</p><p></p><div class=\"verbatim\">\n<pre>_CONDOR_SEC_DEFAULT_AUTHENTICATION=R _CONDOR_TOOL_DEBUG=D_ALL condor_q -debug -name submit-3.batlab.org\n</pre></div>\n\n\n<p>reproduced the problem with condor_q.\n\n</p><p></p><hr/>\n<em>2015-Apr-22 17:13:47 by tlmiller:</em> <br/>\n\nThis appears to fail with the 8.3.5 binaries.\n\n<p></p><hr/>\n<em>2015-Apr-22 17:34:03 by tlmiller:</em> <br/>\n\nDoes not appear to happen with the BaTLab's 8.2.7 daemons in production.\n\n<p></p><hr/>\n<em>2015-Apr-29 15:11:42 by bbockelm:</em> <br/>\n\nWas not able to reproduce with GSI auth on the CMS global pool.\n\n<p></p><hr/>\n<em>2015-Apr-29 15:12:17 by tannenba:</em> <br/>\n\nRelated at all to <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=4997\" onclick=\"get_ticket_and_populate_wrapper('4997'); return false;\" title=\"Infinite loop in condor_ssh_to_job\">#4997</a></span> ?\n\n<p></p><hr/>\n<em>2015-Apr-29 15:47:00 by tlmiller:</em> <br/>\n\nZach was going to look into this, since it seems like a bug in the security code.\n\n<p></p><hr/>\n<em>2015-Apr-29 15:52:40 by tlmiller:</em> <br/>\n\nApparently the description isn't clear: the bug only occurs if authentication fails (perhaps only if authentication can't succeed, e.g., no GSI or Kerberos authtokens).  However, since this is very easy for an attacker to arrange...\n\n<p></p><hr/>\n<em>2015-May-27 13:39:19 by tlmiller:</em> <br/>\n\n(No, it's unrelated to <span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=4997\" onclick=\"get_ticket_and_populate_wrapper('4997'); return false;\" title=\"Infinite loop in condor_ssh_to_job\">#4997</a></span>.)</blockquote>", "derived_tickets": "", "attachments": "", "check_ins": "", "type": "defect", "last_change": "2015-May-27 13:39", "status": "new", "created": "2015-Apr-22 16:18", "fixed_version": "2015-Apr-22 16:18", "broken_version": "", "priority": "4", "subsystem": "DaemonsSubmitNode", "assigned_to": "zmiller", "derived_from": "", "creator": "tlmiller", "rust": "", "customer_group": "other", "visibility": "public", "notify": "tlmiller@cs.wisc.edu, zmiller@cs.wisc.edu", "due_date": ""}