{"id": 7198, "title": "Ticket #7198: Schedd asserts after passing (null) as its public command port to shad", "description": "<blockquote>\nLIGO reported their schedd crashed and restarted.  Logs showed the schedd asserted with shadow exited with incorrect usage\n\n<p>after the shadow returned JOB_SHADOW_USAGE\n\n</p><p>and logged\n</p><div class=\"code\">\n<pre class=\"code\">08/06/19 14:55:30 ERROR: invalid public schedd_addr specified: --schedd=(null)\n08/06/19 14:55:30 Usage: condor_shadow cluster.proc schedd_addr file_name\n08/06/19 14:55:30 argv[0] = condor_shadow\n08/06/19 14:55:30 argv[1] = 37268058.0\n08/06/19 14:55:30 argv[2] = --reconnect\n08/06/19 14:55:30 argv[3] = --schedd=(null)\n08/06/19 14:55:30 argv[4] = --xfer-queue=limit=upload,download;addr=&lt;10.14.0.52:16411&gt;\n08/06/19 14:55:30 argv[5] = &lt;10.14.0.52:16411&gt;\n08/06/19 14:55:30 argv[6] = -\n\n</pre></div>\n\n\n<p>Also note at this time the SPOOL directory was full, and the schedd was logging a lot of disk full errors.  Things seemed to get better after the schedd restart.</p></blockquote>", "remarks": "<blockquote>\nClosing unless/until it happens again.</blockquote>", "derived_tickets": "", "attachments": "", "check_ins": "", "type": "defect", "last_change": "2019-Oct-01 10:28", "status": "abandoned", "created": "2019-Aug-08 11:01", "fixed_version": "2019-Aug-08 11:01", "broken_version": "v080800", "priority": "3", "subsystem": "DaemonsSubmitNode", "assigned_to": "gthain", "derived_from": "", "creator": "gthain", "rust": "", "customer_group": "ligo", "visibility": "public", "notify": "", "due_date": ""}