{"id": 324, "title": "Ticket #324: Race condition in condor_config when two or more running", "description": "<blockquote>\nOccasionally, the test suite will die in remote_pre while running condor configure with the error \"Unable to open file in /tmp directory!\" in the error output file.  condor_configure is trying to open a file named /tmp/set_config_value.temp.  My guess is that two are running at once, and stepping on each other.  Sticking the pid at the end of this filename should do the trick.</blockquote>", "remarks": "<blockquote>\n</blockquote>", "derived_tickets": "", "attachments": "<html><head></head><body></body></html>", "check_ins": "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n<tbody><tr><td align=\"right\" valign=\"top\" width=\"160\">2009-Mar-15 08:06</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/fc747cf002556d09f78ccb9111808e29fa1686dd\">[14235]</a></span>: Fix race condition in condor_configure (<span class=\"ticket\"><a class=\"resolved\" href=\"/tickets?ticket=324\" onclick=\"get_ticket_and_populate_wrapper('324'); return false;\" title=\"Race condition in condor_config when two or more running\">#324</a></span>)  (By Greg Thain )</td></tr>\n</tbody></table>", "type": "defect", "last_change": "2010-Jan-29 16:45", "status": "resolved", "created": "2009-Mar-15 08:02", "fixed_version": "2009-Mar-15 08:02", "broken_version": "v070200", "priority": "4", "subsystem": "Unknown", "assigned_to": "gthain", "derived_from": "", "creator": "gthain", "rust": "", "customer_group": "other", "visibility": "public", "notify": "", "due_date": ""}