{"id": 4869, "title": "Ticket #4869: Unable to restart ProcD in ShadowLog", "description": "<blockquote>\nWe are seeing frequent cases of the following:\n\n<p></p><div class=\"verbatim\">\n<pre>02/05/15 09:38:04 ** PID = 11921\n02/05/15 09:38:06 (117967.66) (11921): Request to run on glidein_124437_293271930@wn221.datagrid.cea.fr &lt;192.54.207.101:49039?CCBID=128.142.141.17:9824#101681%20128.142.141.24:9824#97995&amp;noUDP&gt; was ACCEPTED\n02/05/15 09:38:12 (117967.66) (11921): File transfer completed successfully.\n02/05/15 12:05:46 (117967.66) (11921): ERROR \"Error from glidein_124437_293271930@wn221.datagrid.cea.fr: unable to restart the ProcD after several tries\" at line 558 in file /slots/03/dir_59220/userdir/src/condor_shadow.V6.1/pseudo_ops.cpp\n</pre></div>\n\n\n<p>It's not clear why, but glidein-based condor_procds appear to be somewhat problematic (appears to be at the &lt;1% level).  More logs as we discover them - but certainly a better log message would be a start.</p></blockquote>", "remarks": "<blockquote>\n</blockquote>", "derived_tickets": "", "attachments": "", "check_ins": "", "type": "incident", "last_change": "2015-Feb-05 12:53", "status": "new", "created": "2015-Feb-05 12:53", "fixed_version": "2015-Feb-05 12:53", "broken_version": "", "priority": "4", "subsystem": "DaemonsExecNode", "assigned_to": "", "derived_from": "#4490", "creator": "bbockelm", "rust": "", "customer_group": "cms", "visibility": "public", "notify": "", "due_date": ""}