{"id": 7337, "title": "Ticket #7337: Creating a DAG submit object with bindings kills Python if it fails", "description": "<blockquote>\nIf I try to create a submit object using the new <code>from_dag</code> method, it can fail if the dag submit file it would generate already exists:\n\n<p></p><div class=\"code\">\n<pre class=\"code\">jovyan@50470e00a878:~/htcondor-dags/examples/mandelbrot/mandelbrot-dag$ ll\ntotal 0\ndrwxrwxrwx 1 jovyan 1000 4096 Oct 23 18:37 ./\ndrwxrwxrwx 1 jovyan 1000 4096 Oct 23 18:37 ../\n-rwxrwxrwx 1 jovyan 1000  491 Oct 23 18:37 dagfile.dag*\n-rwxrwxrwx 1 jovyan 1000 1521 Oct 23 18:36 dagfile.dag.condor.sub*\ndrwxrwxrwx 1 jovyan 1000 4096 Oct 23 18:37 .ipynb_checkpoints/\n-rwxrwxrwx 1 jovyan 1000  394 Oct 23 18:37 montage.sub*\n-rwxrwxrwx 1 jovyan 1000  273 Oct 23 18:37 tile.sub*\n\njovyan@50470e00a878:~/htcondor-dags/examples/mandelbrot/mandelbrot-dag$ python\nPython 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)\n[GCC 7.3.0] :: Anaconda, Inc. on linux\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n&gt;&gt;&gt; import htcondor\n&gt;&gt;&gt; htcondor.__version__\n'8.9.4'\n&gt;&gt;&gt; s = htcondor.Submit.from_dag('dagfile.dag')\nERROR: \"dagfile.dag.condor.sub\" already exists.\n\nSome file(s) needed by condor_dagman already exist.  Either rename them,\nor set the { \"force\" : 1 } option to force them to be overwritten.\n</pre></div>\n\n\n<p>Notice that Python immediately died, with no exception to catch and recover from. I imagine its exiting from inside the bindings whenever something goes wrong, like <code>condor_submit_dag</code> would. Instead, this kind of error should be caught and an exception should be raised so that users can handle it from inside Python.</p></blockquote>", "remarks": "<blockquote>\n<em>2020-Jan-31 10:11:28 by coatsworth:</em> <br/>\n\nGood catch. I've fixed this so the Python bindings now raise an exception on error. <code>condor_submit_dag</code> still fails immediately on error like it did before.\n\n<p></p><hr/>\n<em>2020-Jan-31 11:07:39 by karpel:</em> <br/>\n\nAny chance we could use a more concrete exception than <code>RuntimeError</code>? I understand it may be hard to get the information out of the C++ layer that would let us raise a more specific exception, but if possible, we should do it.\n\n<p><a class=\"external\" href=\"https://docs.python.org/3/library/exceptions.html#FileExistsError\">https://docs.python.org/3/library/exceptions.html#FileExistsError</a> and its cousins might be appropriate\n</p><hr/>\n<em>2020-Apr-10 07:46:37 by tim:</em> <br/>\n\nBulk change of target version from v080906 to v080907 using ticket-target-mover.</blockquote>", "derived_tickets": "", "attachments": "<html><head></head><body></body></html>", "check_ins": "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n<tbody><tr><td align=\"right\" valign=\"top\" width=\"160\">2020-Apr-15 17:11</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/5c84a7b9ada77cfff4371a802d36f21833cfaee2\">[59360]</a></span>: Merged <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/daf924eec055f39dc144151a30cdf013854e5eb6\">[59358]</a></span>, Merge branch 'V8_9_7-branch', added version history (<span class=\"ticket\"><a class=\"resolved\" href=\"/wiki-archive/tickets/?ticket=7337\" onclick=\"get_ticket_and_populate_wrapper('7337'); return false;\" title=\"Creating a DAG submit object with bindings kills Python if it fails\">#7337</a></span>)  (By Mark Coatsworth )</td></tr>\n<tr><td align=\"right\" valign=\"top\" width=\"160\">2020-Apr-15 17:10</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/86dfc2d56a3b0996f14310bfa75d57956523ea1e\">[59359]</a></span>: Added version history (<span class=\"ticket\"><a class=\"resolved\" href=\"/wiki-archive/tickets/?ticket=7337\" onclick=\"get_ticket_and_populate_wrapper('7337'); return false;\" title=\"Creating a DAG submit object with bindings kills Python if it fails\">#7337</a></span>)  (By Mark Coatsworth )</td></tr>\n<tr><td align=\"right\" valign=\"top\" width=\"160\">2020-Jan-31 10:10</td>\n<td align=\"center\" valign=\"top\" width=\"30\">\n<span class=\"icon dot\">\u00a0</span></td>\n<td align=\"left\" valign=\"top\"> \nCheck-in <span class=\"chng\"><a href=\"https://github.com/htcondor/htcondor/commit/77ecfc7f8641f9dea08757148617d808a614ebd9\">[58878]</a></span>: Python DAG submit object now raises exception on error (<span class=\"ticket\"><a class=\"resolved\" href=\"/wiki-archive/tickets/?ticket=7337\" onclick=\"get_ticket_and_populate_wrapper('7337'); return false;\" title=\"Creating a DAG submit object with bindings kills Python if it fails\">#7337</a></span>)  (By Mark Coatsworth )</td></tr>\n</tbody></table>", "type": "defect", "last_change": "2020-Apr-16 14:09", "status": "resolved", "created": "2019-Oct-23 13:46", "fixed_version": "2019-Oct-23 13:46", "broken_version": "v080903", "priority": "2", "subsystem": "PythonBinding", "assigned_to": "coatsworth", "derived_from": "#6275", "creator": "karpel", "rust": "", "customer_group": "other", "visibility": "public", "notify": "karpel@wisc.edu coatsworth@cs.wisc.edu", "due_date": ""}